import turtle
heart = turtle.Turtle()
heart.color('red')
heart.begin_fill()
heart.left(140)
heart.forward(180)
heart.circle(-90, 200)
heart.setheading(60)
heart.circle(-90, 200)
heart.forward(180)
heart.end_fill()
heart.hideturtle()
turtle.done()